services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.1.0'
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: 'confluentinc/cp-kafka:7.1.0'
    container_name: bigg-kafka
    depends_on:
      - zookeeper
    ports: 
      - '29092:29092'
    expose:
      - '9092:9029'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  bigg-ingestor:
    image: bigg-ingestor:1.0-SNAPSHOT
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC: bigg
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092


