name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: biggregistry.azurecr.io
          username: biggregistry
          password: ${{ secrets.BIGG_REGISTRY_PASSWORD  }}
          
